#!/bin/bash

CONEXP_CLJ_HOME=$(dirname $(readlink -f $0))/../
CONEXP_CLJ_INIT=${CONEXP_CLJ_HOME}/lib/conexp-clj.clj

java -Dawt.useSystemAAFontSettings=on -cp ${CONEXP_CLJ_HOME}/lib/\* reply.ReplyMain --init ${CONEXP_CLJ_INIT} $*
